basePath: /api/v1
definitions:
  server.CreateProductRequest:
    properties:
      current_price:
        minimum: 0
        type: integer
      description:
        type: string
      images:
        items:
          type: string
        maxItems: 5
        minItems: 1
        type: array
      min_price:
        minimum: 0
        type: integer
      title:
        maxLength: 200
        minLength: 3
        type: string
    required:
    - current_price
    - images
    - min_price
    - title
    type: object
  server.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  server.LoginUserRequest:
    properties:
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  server.PlaceBidRequest:
    properties:
      bid_amount:
        type: integer
    required:
    - bid_amount
    type: object
host: localhost:8080
info:
  contact:
    email: support.query@e-auc.fun
    name: API Support
    url: http://www.e-auction.local/support
  description: This is a sample server for an e-auction platform.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://e-auction.local/terms/
  title: E-Auction API
  version: 0.0.1
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user with username and password
      parameters:
      - description: User login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/server.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Login a User
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout the user by blacklisting the access token and clearing the
        refresh token cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Logout User
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh the access token using a valid refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Refresh Access Token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email, username, and password
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/server.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
      summary: Register a new User
      tags:
      - Auth
  /products:
    post:
      consumes:
      - application/json
      description: Create a new product listing
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/server.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Create a new Product
      tags:
      - Products
  /products/{productId}:
    get:
      consumes:
      - application/json
      description: Retrieve a specific product by the given product ID
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Product by ID
      tags:
      - Products
  /products/{productId}/bid:
    patch:
      consumes:
      - application/json
      description: Place a bid(update current price) on a specific product by the
        given product ID
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: string
      - description: Bid details
        in: body
        name: bid
        required: true
        schema:
          $ref: '#/definitions/server.PlaceBidRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Place a Bid on a Product
      tags:
      - Products
  /products/{productId}/images:
    get:
      consumes:
      - application/json
      description: Retrieve image URLs for a specific product by the given product
        ID
      parameters:
      - description: Product ID
        in: path
        name: productId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Product Image URLs
      tags:
      - Products
  /products/{sellerId}:
    get:
      consumes:
      - application/json
      description: Retrieve products listed by a specific seller. If no seller ID
        is provided, retrieves products for the current user.
      parameters:
      - description: Seller ID
        in: path
        name: sellerId
        type: string
      - description: Number of products to return
        in: query
        name: limit
        type: integer
      - description: Number of products to skip
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Products by Seller ID
      tags:
      - Products
  /products/upload-images:
    post:
      consumes:
      - multipart/form-data
      description: Upload images for a product
      parameters:
      - description: Product images
        in: formData
        name: images
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Upload Product Images
      tags:
      - Products
  /users/me:
    get:
      description: Retrieve the profile information of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
      summary: Get User Profile
      tags:
      - Users
swagger: "2.0"
